### ISSUE TITLE
Mouseclicks are offset (at least vertically)

### ISSUE THREAD

**Issue by lesleyrs** [max-m/SameBoy#89]
Not sure about the cause, noticed when going through escape menu.

**Comment by max-m** [comment]
Hi!
I think I’ve seen this behavior before, but as far as I remember this only happens sporadically?
When I checked a couple of minutes ago on my desktop in Firefox the mouse coordinates in the menu seemed to work fine.

This repository is also more or less in low maintenance mode as I plan to replace it with a completely rewritten codebase, based on the iOS frontend. :smile:

**Comment by lesleyrs** [comment]
On both Android and Windows it has the same issue for me, even on Firefox. I'll close issue though since it won't matter after rewrite. But for example if I click at the bottom of the black square game window it opens sponsors, so they're offset quite a lot, not sporadic.
